import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import { arSA } from "@clerk/localizations";
import "./globals.css";
import Sidebar from "@/components/layout/sidebar";
import Header from "@/components/layout/header";
import { ThemeProvider } from "@/components/theme-provider";
import BreadCrumb from "@/components/layout/BreadCrumb";
import { DashboardProvider } from "@/contexts/DashboardContext";
import { Toaster } from "@/components/ui/toaster";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <DashboardProvider>
        <html lang="fa" dir="rtl">
          <body>
            <ThemeProvider
              attribute="class"
              defaultTheme="light"
              disableTransitionOnChange
            >
              <div className="grid min-h-screen w-full md:grid-cols-[220px_1fr] lg:grid-cols-[280px_1fr]">
                <Sidebar />
                <div className="flex flex-col">
                  <Header />
                  <main className="flex flex-1 flex-col gap-4 p-4 lg:gap-6 lg:p-6 h-full">
                    <div className="flex items-center">
                      <BreadCrumb />
                    </div>
                    <div className="flex flex-1 items-center justify-center bg-white rounded-lg border border-dashed border-primary shadow-sm max-h-fit h-fit">
                      {children}
                    </div>
                  </main>
                </div>
              </div>
              <Toaster />
            </ThemeProvider>
          </body>
        </html>
      </DashboardProvider>
    </ClerkProvider>
  );
}
